on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
     -
      name: Set up CoPilot JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
     -
      name: Upload to CoPilot
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)